services:
  celery-backend:
    build:
      context: "./backend"
      dockerfile: celery.dockerfile
    container_name: celery-backend
    depends_on:
      - redis
    networks:
      - backend

  fastapi-backend:
    build:
      context: "./backend"
      dockerfile: fastapi.dockerfile
    container_name: fastapi-backend
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    networks:
      - backend

  react-frontend:
    build:
      context: "./frontend"
      dockerfile: react.dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    ports: 
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis
    networks:
      - backend

networks:
  backend:

volumes:
  mongo-data: